buildscript {
    ext.kotlin_version = '2.2.0'
    ext.core_ktx_version = '1.12.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

ext {
    sdk = [
        compileSdk: 36,
        targetSdk : 36,
        minSdk    : 21
    ]
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
